[project]
name = "proyecto-bi-manfred"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "jupyter>=1.1.1",
    "pandas>=2.3.3",
    "playwright>=1.57.0",
    "matplotlib>=3.8.0",
    "seaborn>=0.13.0",
]
